<?php
/**
 * @file
 * scale_schedule.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function scale_schedule_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-schedule-13x_friday-february-20-2015:scale/13x/schedule/friday.
  $menu_links['menu-schedule-13x_friday-february-20-2015:scale/13x/schedule/friday'] = array(
    'menu_name' => 'menu-schedule-13x',
    'link_path' => 'scale/13x/schedule/friday',
    'router_path' => 'scale/13x/schedule',
    'link_title' => 'Friday, February 20, 2015',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-13x_friday-february-20-2015:scale/13x/schedule/friday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-13x_saturday-february-21-2015:scale/13x/schedule/saturday.
  $menu_links['menu-schedule-13x_saturday-february-21-2015:scale/13x/schedule/saturday'] = array(
    'menu_name' => 'menu-schedule-13x',
    'link_path' => 'scale/13x/schedule/saturday',
    'router_path' => 'scale/13x/schedule',
    'link_title' => 'Saturday, February 21, 2015',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-13x_saturday-february-21-2015:scale/13x/schedule/saturday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-13x_sunday-february-22-2015:scale/13x/schedule/sunday.
  $menu_links['menu-schedule-13x_sunday-february-22-2015:scale/13x/schedule/sunday'] = array(
    'menu_name' => 'menu-schedule-13x',
    'link_path' => 'scale/13x/schedule/sunday',
    'router_path' => 'scale/13x/schedule',
    'link_title' => 'Sunday, February 22, 2015',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-13x_sunday-february-22-2015:scale/13x/schedule/sunday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-13x_thursday-february-19-2015:scale/13x/schedule/thursday.
  $menu_links['menu-schedule-13x_thursday-february-19-2015:scale/13x/schedule/thursday'] = array(
    'menu_name' => 'menu-schedule-13x',
    'link_path' => 'scale/13x/schedule/thursday',
    'router_path' => 'scale/13x/schedule',
    'link_title' => 'Thursday, February 19, 2015',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-13x_thursday-february-19-2015:scale/13x/schedule/thursday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-14x_friday-january--22-2016:scale/14x/schedule/friday.
  $menu_links['menu-schedule-14x_friday-january--22-2016:scale/14x/schedule/friday'] = array(
    'menu_name' => 'menu-schedule-14x',
    'link_path' => 'scale/14x/schedule/friday',
    'router_path' => 'scale/14x/schedule',
    'link_title' => 'Friday, January  22, 2016',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-14x_friday-january--22-2016:scale/14x/schedule/friday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-14x_saturday-january--23-2016:scale/14x/schedule/saturday.
  $menu_links['menu-schedule-14x_saturday-january--23-2016:scale/14x/schedule/saturday'] = array(
    'menu_name' => 'menu-schedule-14x',
    'link_path' => 'scale/14x/schedule/saturday',
    'router_path' => 'scale/14x/schedule',
    'link_title' => 'Saturday, January  23, 2016',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-14x_saturday-january--23-2016:scale/14x/schedule/saturday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-14x_sunday-january--24-2016:scale/14x/schedule/sunday.
  $menu_links['menu-schedule-14x_sunday-january--24-2016:scale/14x/schedule/sunday'] = array(
    'menu_name' => 'menu-schedule-14x',
    'link_path' => 'scale/14x/schedule/sunday',
    'router_path' => 'scale/14x/schedule',
    'link_title' => 'Sunday, January  24, 2016',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-14x_sunday-january--24-2016:scale/14x/schedule/sunday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-schedule-14x_thursday-january--21-2016:scale/14x/schedule/thursday.
  $menu_links['menu-schedule-14x_thursday-january--21-2016:scale/14x/schedule/thursday'] = array(
    'menu_name' => 'menu-schedule-14x',
    'link_path' => 'scale/14x/schedule/thursday',
    'router_path' => 'scale/14x/schedule',
    'link_title' => 'Thursday, January  21, 2016',
    'options' => array(
      'attributes' => array(
        'class' => array(
          0 => 'btn',
        ),
      ),
      'identifier' => 'menu-schedule-14x_thursday-january--21-2016:scale/14x/schedule/thursday',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Friday, February 20, 2015');
  t('Friday, January  22, 2016');
  t('Saturday, February 21, 2015');
  t('Saturday, January  23, 2016');
  t('Sunday, February 22, 2015');
  t('Sunday, January  24, 2016');
  t('Thursday, February 19, 2015');
  t('Thursday, January  21, 2016');

  return $menu_links;
}
