<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_access().
 */
function custom_access_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $bundle = $node->bundle();
  $service_id = "custom_access.user_access_" . $bundle;

  if (\Drupal::hasService($service_id)) {
    $service = \Drupal::service($service_id);
    return $service->checkAccess($node, $op, $account);
  }

  return AccessResult::neutral();
}
