name: scale10
recipe: drupal10
config:
  webroot: web
  xdebug: true
  config:
    php: .lando.php.ini
  services:
    phpmyadmin:
      type: phpmyadmin
tooling:
  drush:
    service: appserver
    cmd: drush
    env:
      DRUSH_OPTIONS_URI: scale10.lndo.site
events:
  pre-db-import:
    # Fix MySQL 8 import issue (dropping DB with Drush).
    - appserver: echo "Dropping DB" && $LANDO_WEBROOT/../vendor/bin/drush sql:drop -y
