name: scale10
recipe: pantheon
config:
  framework: drupal8
  site: scale-conf
  id: 247425fd-b327-4b33-915d-e7f6a2b53818
  # Disable the SOLR index
  index: false
  # Disable the VARNISH edge
  edge: false
  # Disable the REDIS cache
  cache: false
  webroot: web
  xdebug: true
  config:
    php: .lando.php.ini
  services:
    phpmyadmin:
      type: phpmyadmin
tooling:
  drush:
    service: appserver
    cmd: drush
    env:
      DRUSH_OPTIONS_URI: scale10.lndo.site
events:
  pre-db-import:
    # Fix MySQL 8 import issue (dropping DB with Drush).
    - appserver: echo "Dropping DB" && $LANDO_WEBROOT/../vendor/bin/drush sql:drop -y
