<?php

/**
 * Implements hook_theme().
 */
function views_plugins_theme($existing, $type, $theme, $path) {
  return [
    'views_swiperjs' => [
      'variables' => ['view' => NULL, 'rows' => NULL],
    ],
  ];
}

/**
 * Prepares variables for views views_swiperjs template.
 *
 * Template: views-swiperjs.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: The view object.
 *   - rows: An array of row items. Each row is an array of content.
 */
function views_plugins_preprocess_views_swiperjs(&$variables) {
  $view = $variables['view'];
//  $rows = $variables['rows'];

  $pagination = $view->style_plugin->options['pagination'];
  $navigation = $view->style_plugin->options['navigation'];
  $scrollbar = $view->style_plugin->options['scrollbar'];

  template_preprocess_views_view_unformatted($variables);

  $variables['navigation'] = $navigation;
  $variables['scrollbar'] = $scrollbar;
  $variables['pagination'] = $pagination;
}
