<?php

/**
 * Implements hook_theme().
 */
function hero_block_theme($existing, $type, $theme, $path) {
  return [
    'hero_block' => [
      'variables' => ['title' => NULL, 'node' => NULL, 'content' => NULL],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for block templates.
 */
function hero_block_theme_suggestions_hero_block_alter(array &$suggestions, array $variables): void {
  // Add hero block template suggestions based on the content type.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $content_type = $node->getType();
    $suggestions[] = 'hero_block__' . $content_type;
  }
}


/**
 * Implements theme_preprocess_HOOK().
 */
function hero_block_preprocess_hero_block__session(&$variables) {
  /** @var \Drupal\node\Entity\Node $ndoe */
  $node = $variables["node"];

  // Get speakers and render the nodes using the listing view mode
  $speakers = $node->get('field_speakers_ref')->referencedEntities();
  $speaker_nodes = [];
  foreach ($speakers as $speaker) {
    $speaker_nodes[] = \Drupal::entityTypeManager()
      ->getViewBuilder('node')
      ->view($speaker, 'listing_small');
  }

  $variables['content']['speakers'] = $speaker_nodes;
}
