<?php

/**
 * Implements hook_theme().
 */
function hero_block_theme($existing, $type, $theme, $path) {
  return [
    'hero_block' => [
      'variables' => ['title' => NULL, 'node' => NULL, 'content' => NULL],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for block templates.
 */
function hero_block_theme_suggestions_hero_block_alter(array &$suggestions, array $variables): void {
  // Add hero block template suggestions based on the content type.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $content_type = $node->getType();
    $suggestions[] = 'hero_block__' . $content_type;
  }
}


/**
 * Implements theme_preprocess_HOOK().
 */
function hero_block_preprocess_hero_block__session(&$variables): void {
  /** @var \Drupal\node\Entity\Node $ndoe */
  $node = $variables["node"];

  // Get speakers and render the nodes using the listing view mode
  $speakers = $node->get('field_speakers_ref')->referencedEntities();
  $speaker_nodes = [];
  foreach ($speakers as $speaker) {
    $speaker_nodes[] = \Drupal::entityTypeManager()
      ->getViewBuilder('node')
      ->view($speaker, 'listing_small');
  }

  $variables['content']['speakers'] = $speaker_nodes;
}

/**
 * Implements theme_preprocess_HOOK().
 */
function hero_block_preprocess_hero_block__sponsor(&$variables): void {
  /** @var \Drupal\node\Entity\Node $ndoe */
  $node = $variables["node"];

  $sponsor_type_entities = $node->get('field_sponsor_type')->referencedEntities();
  $sponsor_types = [];
  foreach ($sponsor_type_entities as $sponsor_type) {
    $sponsor_types[] = $sponsor_type->label();
  }

  $variables['content']['sponsor_types'] = $sponsor_types;
}

/**
 * Implements theme_preprocess_HOOK().
 */
function hero_block_preprocess_hero_block__landing_page(&$variables): void {
  /** @var \Drupal\node\Entity\Node $ndoe */
  $node = $variables["node"];

  // Ensure the field_image field exists and is not empty.
  if ($node->hasField('field_image') && !$node->get('field_image')->isEmpty()) {
    // Load the image file entity.
    $file = $node->get('field_image')->entity;

    if ($file instanceof \Drupal\file\Entity\File) {
      // Generate the image URL with the 'wide' image style.
      $image_style = \Drupal::entityTypeManager()->getStorage('image_style')->load('wide');
      if ($image_style) {
        $image_url = $image_style->buildUrl($file->getFileUri());
        // Add the URL to the variables for the template.
        $variables['hero_image_url'] = $image_url;
      }
    }
  }
}
