<?php

use Drupal\Core\Database\Database;
use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\MigrateMessage;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function d10_migration_preprocess_page(&$variables) {
//  $migration_id = 'type_session';
//  $migration = \Drupal::service('plugin.manager.migration')->createInstance($migration_id);
//  $migration->getIdMap()->prepareUpdate();
//  $executable = new MigrateExecutable($migration, new MigrateMessage());
//  $executable->import();
}
